version: 2
registries:
  shared-resources:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.DEPENDABOT_GITHUB_PAT}}

updates:

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    registries: 
      - "shared-resources"
    schedule:
      interval: "weekly"
