# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "ims-infra-base-state-common-us-east-1"
    dynamodb_table = "ims-infra-base-state-lock"
    encrypt        = true
    key            = "common/_global/iam/terraform.tfstate"
    region         = "us-east-1"
  }
}
